apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-simples
  namespace: meu-cloud-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-simples
  template:
    metadata:
      labels:
        app: node-simples
    spec:
      containers:
      - name: node
        image: node-simples:22
        ports:
        - containerPort: 3004
